/**
 * Stub for the build-time `virtual:theme-templates` module.
 *
 * The real module is generated by src/integrations/theme-loader.ts and maps
 * theme ids to their Astro template components. Render tests target an explicit
 * component instead of a theme registry lookup, so the map can stay empty.
 */
export const themeTemplates: Record<string, Record<string, unknown>> = {};
