/**
 * Plugin system - discovers and manages plugins from npm packages
 * 
 * Plugin packages are identified by their package.json keywords
 * containing both "typecho" and "plugin".
 * 
 * Hook types (following Typecho conventions):
 * - call: Action hooks - execute side effects at specific points
 * - filter: Filter hooks - transform data through a chain of handlers
 * 
 * Plugin package structure:
 *   typecho-plugin-example/
 *     package.json       - Must have keywords: ["typecho", "plugin"] + typecho.plugin manifest
 *     index.ts/js        - Plugin entry point (required)
 */

import {
  getConfigDefaults,
  loadConfig,
  parseConfigFormData,
  type ConfigField,
} from '@/lib/config';
import {
  beginPluginTranslationStage,
  commitPluginTranslationStage,
  discardPluginTranslationStage,
  getAvailableTranslationLocales,
  getGlobalTranslationCatalogs,
  getTranslationCatalogVersion,
  resetPluginTranslationRegistry,
  stagePluginTranslation,
} from '@/lib/i18n-registry';
import type { I18n, ResolvedLocale } from '@/lib/i18n';
import { env as runtimeEnv } from 'cloudflare:workers';
import {
  enqueueAsyncTaskMessage,
  type EnqueueAsyncTaskOptions,
} from '@/lib/tasks/enqueue';
import {
  registerAsyncTask,
  registerScheduledTask,
  resetTaskRegistrations,
  resetTaskRegistry,
} from '@/lib/tasks/registry';
import type {
  AsyncTaskDefinition,
  ScheduledTaskDefinition,
} from '@/lib/tasks/types';
import {
  clearPluginRouteClaims,
  markPluginRouteResolverReady,
  registerPluginRouteResolver,
  resetPluginRouteRegistry,
} from '@/lib/plugin-routes';
import type { PluginRouteClaim, PluginRouteResolver } from '@/lib/plugin-routes';
import {
  registerCapability as registerOwnedCapability,
  resetCapabilityRegistry,
  setCapabilityActivation,
  unregisterCapabilityOwner,
} from '@/lib/capability';
import type { CapabilityRegistration } from '@/lib/capability';
import type { CapabilityRuntimeContext } from '@/lib/capability';
import { addHook, applyFilterSafely, HookPoints, removePluginHooks } from '@/lib/hooks';
import {
  planPluginActivation,
  planPluginActivationAction,
  type PluginActivationActionPlan,
  type PluginActivationPlan,
  type PluginDependency,
  type PluginDependencyIssue,
  type PluginDependencyNode,
} from '@/lib/plugin-dependencies';
export {
  getPluginRouteClaimsSnapshot,
  isPluginRoute,
  refreshPluginRoutes,
} from '@/lib/plugin-routes';
export type {
  PluginRouteClaim,
  PluginRouteResolver,
  PluginRouteResolverContext,
} from '@/lib/plugin-routes';
export {
  getAvailableTranslationLocales,
  getGlobalTranslationCatalogs,
  getTranslationCatalogVersion,
} from '@/lib/i18n-registry';
export type { AvailableTranslationLocale, PluginTranslationRegistration } from '@/lib/i18n-registry';
export {
  HookPoints,
  addHook,
  applyFilter,
  applyFilterSafely,
  doHook,
  getRegisteredHooks,
  hasHook,
  normalizeHookPoint,
  removePluginHooks,
} from '@/lib/hooks';
export type { CallHandler, FilterHandler, HookPoint } from '@/lib/hooks';

// ==================== Types ====================

/** Internal form metadata used to preserve repeatable rows across reordering. */
export { CONFIG_ROW_ID as PLUGIN_CONFIG_ROW_ID } from '@/lib/config';

/**
 * Plugin configuration field definition.
 * Mirrors PHP Typecho's Form Element types; shared with theme config.
 */
export type PluginConfigField = ConfigField;

export interface PluginManifest {
  /** Unique plugin identifier */
  id: string;
  /** Display name */
  name: string;
  /** Plugin description */
  description?: string;
  /** Author name */
  author?: string;
  /** Author URL */
  authorUrl?: string;
  /** Plugin version */
  version?: string;
  /** Plugin homepage / repository URL */
  homepage?: string;
  /** License */
  license?: string;
  /** Tags for categorization */
  tags?: string[];
  /** Required Typecho version */
  requires?: string;
  /**
   * Plugin configuration fields.
   * If present, the admin panel shows a "设置" link for this plugin.
   * Keys are field names, values are field definitions.
   * Stored as JSON in options table under key "plugin:<id>".
   */
  config?: Record<string, PluginConfigField>;
}

export interface PluginInfo {
  /** Plugin ID (slug) */
  id: string;
  /** npm package name */
  packageName: string;
  /** Plugin manifest from package.json's typecho.plugin */
  manifest: PluginManifest;
  /** Whether this plugin is currently activated */
  isActive: boolean;
  /** Request-local lifecycle state used by the admin surface. */
  status: PluginRuntimeStatus;
  /** Package-manager dependency metadata generated by plugin-loader. */
  dependencies?: ReadonlyArray<PluginDependency>;
  /** Build-time graph diagnostics that make this plugin unavailable. */
  dependencyIssues?: ReadonlyArray<PluginDependencyIssue>;
}

export type PluginRuntimeStatus =
  | 'active'
  | 'inactive'
  | 'blocked'
  | 'initialization-failed';

/**
 * Hook handler function types
 * - CallHandler: Receives context, no return value expected
 * - FilterHandler: Receives value + context, must return the (possibly modified) value
 */

export interface HookContext {
  activatedPlugins: Set<string>;
  /** Request-scoped generic capability context, when bootstrapped by the host. */
  capabilityRuntime?: CapabilityRuntimeContext;
  /** Requested IDs from the persisted admin intent, before dependency filtering. */
  requestedPlugins?: ReadonlyArray<string>;
  /** Request-local dependency diagnostics for the effective activation plan. */
  activationDiagnostics?: ReadonlyArray<PluginDependencyIssue>;
  /** Generation used to bind request-scoped capabilities. */
  activationGeneration?: number;
  /** Request-local copy of the route claims used by middleware. */
  routeClaims?: ReadonlyArray<PluginRouteClaim>;
  /** Request-local plugin IDs whose route resolver init failed. */
  routeResolverFailures?: ReadonlySet<string>;
  /** Request-local translator. Minimal test/plugin contexts may omit it. */
  i18n?: I18n;
  resolvedLocale?: ResolvedLocale;
}

export interface PluginInitContext {
  addHook: typeof addHook;
  HookPoints: typeof HookPoints;
  pluginId: string;
  registerRouteResolver: (resolver: PluginRouteResolver) => void;
  /** Declare an owner-scoped /admin/ or /api/admin/ path served via request:route. */
  registerAdminPath: (path: string) => void;
  /** Register a generic capability implementation owned by this plugin. */
  registerCapability?: <T>(
    registration: Omit<CapabilityRegistration<T>, 'ownerPluginId'>,
  ) => void;
  registerTranslations: (
    locale: string,
    messages: Record<string, string>,
    displayName?: string,
  ) => void;
  registerScheduledTask: (definition: ScheduledTaskDefinition) => void;
  registerAsyncTask: <TPayload = unknown>(
    definition: AsyncTaskDefinition<TPayload>,
  ) => void;
  enqueueAsyncTask: <TPayload = unknown>(
    taskId: string,
    payload: TPayload,
    options: EnqueueAsyncTaskOptions,
  ) => Promise<{ jobId: string; taskKey: string; idempotencyKey: string }>;
}

export interface PluginRouteResult {
  handled?: boolean;
  response?: Response;
}

const pluginRegistry = new Map<string, PluginInfo>();

/**
 * Hook handlers registry
 * Key: hook point name, Value: sorted array of handlers
 */
type PluginInitFn = (ctx: PluginInitContext) => void | Promise<void>;
type PluginInitLoader = () => PluginInitFn | Promise<PluginInitFn>;
const pluginInitLoaders = new Map<string, PluginInitLoader>();
const initialisedPlugins = new Set<string>();
const initialisingPlugins = new Map<string, Promise<void>>();
const failedPlugins = new Map<string, { error: string; failedAt: number; attempts: number }>();
/** Backoff base between init retries after a failure (doubles up to 5×). */
const PLUGIN_INIT_FAIL_BACKOFF_MS = 60_000;
let pluginInitContext: { addHook: typeof addHook; HookPoints: typeof HookPoints } | null = null;
let activationSetKey: string | null = null;
let activationGeneration = 0;
/** Effective plugin set from the previous activation-plan rebuild. */
let activePluginIds = new Set<string>();

/** Snapshot of plugins whose lazy init failed (for admin visibility). */
export function getPluginInitFailures(): Record<string, { error: string; attempts: number; failedAt: number }> {
  const out: Record<string, { error: string; attempts: number; failedAt: number }> = {};
  for (const [id, failure] of failedPlugins) {
    out[id] = { error: failure.error, attempts: failure.attempts, failedAt: failure.failedAt };
  }
  return out;
}

/** Test-only: clear init success/failure state. */
export function resetPluginInitState(): void {
  initialisedPlugins.clear();
  initialisingPlugins.clear();
  failedPlugins.clear();
  resetPluginRouteRegistry();
  resetCapabilityRegistry();
  pluginAdminPaths.clear();
  resetTaskRegistry();
  resetPluginTranslationRegistry();
  activationSetKey = null;
  activationGeneration = 0;
  activePluginIds = new Set<string>();
}

/**
 * Owner-scoped admin/API paths that bypass the reserved-core-path guard in
 * middleware. A plugin declares them from its init() through
 * `PluginInitContext.registerAdminPath`; claims are dropped when the plugin is
 * deactivated or fails to initialize, so a disabled plugin never keeps an
 * exemption alive.
 */
const pluginAdminPaths = new Map<string, Set<string>>();

export function registerPluginAdminPath(ownerPluginId: string, path: string): void {
  if (!ownerPluginId || typeof path !== 'string' || !path) return;
  const paths = pluginAdminPaths.get(ownerPluginId) ?? new Set<string>();
  paths.add(path);
  pluginAdminPaths.set(ownerPluginId, paths);
}

export function clearPluginAdminPaths(ownerPluginId: string): void {
  pluginAdminPaths.delete(ownerPluginId);
}

export function isPluginAdminPath(path: string): boolean {
  for (const paths of pluginAdminPaths.values()) {
    if (paths.has(path)) return true;
  }
  return false;
}

/**
 * Backward-compatible registration Interface for tests and integrations that
 * already imported plugin init functions.
 */
export function registerPluginInit(
  inits: Record<string, PluginInitFn>,
  ctx: { addHook: typeof addHook; HookPoints: typeof HookPoints },
): void {
  registerPluginLoaders(
    Object.fromEntries(
      Object.entries(inits).map(([id, init]) => [id, () => init]),
    ),
    ctx,
  );
}

/**
 * Register deferred module loaders generated by plugin-loader. Keeping the
 * loader behind this Interface prevents disabled plugin modules from being
 * evaluated during isolate startup.
 */
export function registerPluginLoaders(
  loaders: Record<string, PluginInitLoader>,
  ctx: { addHook: typeof addHook; HookPoints: typeof HookPoints },
): void {
  pluginInitContext = ctx;
  for (const [id, loader] of Object.entries(loaders)) {
    pluginInitLoaders.set(id, loader);
  }
}

// ==================== Plugin Management ====================

/**
 * Register a plugin into the registry.
 * Called by the plugin-loader integration at build time.
 */
export function registerPlugin(
  packageName: string,
  manifest: PluginManifest,
  dependencyMetadata: {
    dependencies?: ReadonlyArray<PluginDependency>;
    issues?: ReadonlyArray<PluginDependencyIssue>;
  } = {},
): void {
  const id = manifest.id || packageName;
  pluginRegistry.set(id, {
    id,
    packageName,
    manifest: { ...manifest, id },
    isActive: false,
    status: 'inactive',
    dependencies: dependencyMetadata.dependencies,
    dependencyIssues: dependencyMetadata.issues,
  });
}

function pluginDependencyNodes(): Map<string, PluginDependencyNode> {
  const nodes = new Map<string, PluginDependencyNode>();
  for (const [id, info] of pluginRegistry) {
    nodes.set(id, {
      id,
      dependencies: info.dependencies,
      issues: info.dependencyIssues,
    });
  }
  return nodes;
}

function opaquePluginIds(): Set<string> {
  const opaque = new Set<string>();
  for (const id of pluginInitLoaders.keys()) {
    if (!pluginRegistry.has(id)) opaque.add(id);
  }
  return opaque;
}

/** Build the single activation plan used by requests and admin mutations. */
export function getPluginActivationPlan(ids: Iterable<string>): PluginActivationPlan {
  return planPluginActivation(ids, pluginDependencyNodes(), opaquePluginIds());
}

/** Build an enable/disable plan, including required dependent cascades. */
export function getPluginActivationActionPlan(
  ids: Iterable<string>,
  pluginId: string,
  action: 'activate' | 'deactivate',
): PluginActivationActionPlan {
  return planPluginActivationAction(
    ids,
    pluginId,
    action,
    pluginDependencyNodes(),
    opaquePluginIds(),
  );
}

/**
 * Set the list of activated plugin IDs (loaded from DB).
 *
 * G6-3: the first time we see a given plugin in the activated set, we
 * call its init function so its hooks land in hookRegistry. Plugins
 * that are never activated never have their init code run, which keeps
 * the per-isolate startup cost proportional to active plugin count.
 */
export async function setActivatedPlugins(ctx: HookContext, ids: string[]): Promise<void> {
  const requestedIds = [...new Set(ids.filter(id => typeof id === 'string' && id.length > 0))];
  const activationPlan = getPluginActivationPlan(requestedIds);
  const orderedIds = activationPlan.effective;
  const nextActivePluginIds = new Set(orderedIds);
  ctx.requestedPlugins = activationPlan.requested;
  ctx.activationDiagnostics = activationPlan.diagnostics;
  ctx.activatedPlugins = new Set(orderedIds);
  const nextActivationSetKey = [...orderedIds].sort().join('\u0000');
  if (activationSetKey !== nextActivationSetKey) {
    for (const pluginId of activePluginIds) {
      if (nextActivePluginIds.has(pluginId)) continue;
      deactivatePluginRuntime(pluginId);
    }
    activationSetKey = nextActivationSetKey;
    activationGeneration += 1;
    activePluginIds = nextActivePluginIds;
  }
  setCapabilityActivation(ctx.activatedPlugins, activationGeneration);
  ctx.activationGeneration = activationGeneration;
  if (!pluginInitContext) return;
  const dependencyNodes = pluginDependencyNodes();
  for (const id of orderedIds) {
    const dependencyNode = dependencyNodes.get(id);
    if (dependencyNode?.dependencies?.some(dependency => (
      dependency.kind === 'required' && !ctx.activatedPlugins.has(dependency.pluginId)
    ))) {
      // A required provider that failed earlier in this same plan makes its
      // consumer unavailable for this request. The persisted admin intent is
      // left untouched; the next request can retry after the provider recovers.
      ctx.activatedPlugins.delete(id);
      continue;
    }
    if (initialisedPlugins.has(id)) continue;
    const failure = failedPlugins.get(id);
    if (failure) {
      const backoff = PLUGIN_INIT_FAIL_BACKOFF_MS * Math.min(failure.attempts, 5);
      if (Date.now() - failure.failedAt < backoff) {
        // A failed plugin is not active for this request, including while its
        // retry backoff is in effect. The activation set is rebuilt on every
        // request, so this guard must be applied here as well as in catch().
        ctx.activatedPlugins.delete(id);
        continue;
      }
    }
    const existingInit = initialisingPlugins.get(id);
    if (existingInit) {
      await existingInit;
      // Another request may have owned the init attempt. Its catch() only
      // has access to that request's context, so mirror the outcome here.
      if (!initialisedPlugins.has(id)) ctx.activatedPlugins.delete(id);
      continue;
    }
    const loader = pluginInitLoaders.get(id);
    if (!loader) continue;
    const pending = Promise.resolve()
      .then(() => {
        beginPluginTranslationStage(id);
        return loader();
      })
      .then(init => init({
          addHook: pluginInitContext!.addHook,
          HookPoints: pluginInitContext!.HookPoints,
          pluginId: id,
          registerRouteResolver: (resolver: PluginRouteResolver) => {
            registerPluginRouteResolver(id, resolver);
          },
          registerAdminPath: (path: string) => {
            registerPluginAdminPath(id, path);
          },
          registerCapability: <T>(registration: Omit<CapabilityRegistration<T>, 'ownerPluginId'>) => {
            registerOwnedCapability(id, registration);
          },
          registerTranslations: (locale, messages, displayName) => {
            stagePluginTranslation(id, locale, messages, displayName);
          },
          registerScheduledTask: (definition: ScheduledTaskDefinition) => {
            registerScheduledTask(id, definition);
          },
          registerAsyncTask: <TPayload>(definition: AsyncTaskDefinition<TPayload>) => {
            registerAsyncTask(id, definition);
          },
          enqueueAsyncTask: <TPayload>(
            taskId: string,
            payload: TPayload,
            options: EnqueueAsyncTaskOptions,
          ) => enqueueAsyncTaskMessage(runtimeEnv, id, taskId, payload, options),
        }))
      .then(() => {
        commitPluginTranslationStage(id);
        initialisedPlugins.add(id);
        markPluginRouteResolverReady(id);
        failedPlugins.delete(id);
      })
      .catch(err => {
        removePluginHooks(id);
        unregisterCapabilityOwner(id);
        ctx.activatedPlugins.delete(id);
        discardPluginTranslationStage(id);
        clearPluginRouteClaims(id);
        clearPluginAdminPaths(id);
        resetTaskRegistrations(id);
        const message = err instanceof Error ? err.message : String(err);
        const prior = failedPlugins.get(id);
        failedPlugins.set(id, {
          error: message,
          failedAt: Date.now(),
          attempts: (prior?.attempts ?? 0) + 1,
        });
        console.error(`[plugin] Failed to init ${id}:`, err);
      })
      .finally(() => {
        initialisingPlugins.delete(id);
      });
    initialisingPlugins.set(id, pending);
    await pending;
  }
}

/**
 * Tear down request-independent registrations when an active plugin becomes
 * inactive. Hook and task registries are isolate-scoped, so merely removing
 * the ID from one request context would leave stale state to be reused when
 * the plugin is enabled again. Re-enabling therefore runs init() again and
 * creates fresh owner-bound Capability registrations for the new generation.
 */
function deactivatePluginRuntime(pluginId: string): void {
  removePluginHooks(pluginId);
  unregisterCapabilityOwner(pluginId);
  clearPluginRouteClaims(pluginId);
  clearPluginAdminPaths(pluginId);
  resetTaskRegistrations(pluginId);
  initialisedPlugins.delete(pluginId);
  failedPlugins.delete(pluginId);
}

/**
 * Check if a plugin is activated
 */
export function isPluginActive(ctx: HookContext, pluginId: string): boolean {
  return ctx.activatedPlugins.has(pluginId);
}

/**
 * Get all available plugins
 */
export function getAvailablePlugins(ctx: HookContext): PluginInfo[] {
  const plugins: PluginInfo[] = [];
  for (const [, info] of pluginRegistry) {
    const isActive = ctx.activatedPlugins.has(info.id);
    const status: PluginRuntimeStatus = isActive
      ? 'active'
      : failedPlugins.has(info.id)
        ? 'initialization-failed'
        : ctx.requestedPlugins?.includes(info.id)
          ? 'blocked'
          : 'inactive';
    plugins.push({
      ...info,
      isActive,
      status,
    });
  }
  return plugins;
}

/**
 * Get a specific plugin
 */
export function getPlugin(pluginId: string): PluginInfo | undefined {
  return pluginRegistry.get(pluginId);
}

/**
 * Get plugin count
 */
export function getPluginCount(): number {
  return pluginRegistry.size;
}

/**
 * Check if a plugin exists
 */
export function pluginExists(pluginId: string): boolean {
  return pluginRegistry.has(pluginId);
}

// ==================== Hook System ====================

/**
 * Register a hook handler for a specific hook point.
 * Only handlers from activated plugins will be executed.
 *
 * @param hookPoint - The hook point name (use HookPoints constants)
 * @param pluginId - The plugin ID registering this handler
 * @param handler - The handler function
 * @param priority - Execution priority (lower = earlier, default 10)
 *
 * G6-1: dedupes (pluginId, handler-by-reference) so repeated hook
 * registration does not run the handler twice on every request.
 */
export function serializeActivatedPlugins(ctx: HookContext): string {
  return JSON.stringify(Array.from(ctx.activatedPlugins));
}

/**
 * Parse activated plugins list from DB string
 */
export function parseActivatedPlugins(value: string | null | undefined): string[] {
  if (!value) return [];
  try {
    const arr = JSON.parse(value);
    return Array.isArray(arr)
      ? [...new Set(arr.filter(id => typeof id === 'string' && id.length > 0))]
      : [];
  } catch {
    return [];
  }
}

// ==================== Client Snippets ====================

/**
 * Collect client-side HTML snippets from all activated plugins.
 *
 * Plugins register their frontend output by hooking into:
 *   - frontend:head (filter): receives current headHtml, returns headHtml with appended content
 *   - frontend:footer (filter): receives current bodyHtml, returns bodyHtml with appended content
 *
 * This function applies both filters and returns the aggregated result.
 * Themes should call this once and inject the HTML into <head> and before </body>.
 *
 * @param options - Site options object from loadOptions()
 * @returns {{ headHtml: string, bodyHtml: string }}
 */
export interface PageContext {
  /** Whether the current page includes a comment form */
  hasComments?: boolean;
  /** Page type hint for plugins */
  pageType?: 'index' | 'post' | 'page' | 'archive' | 'search' | 'notfound';
}

export async function getClientSnippets(
  ctx: HookContext,
  options: Record<string, any>,
  pageContext?: PageContext,
): Promise<{ headHtml: string; bodyHtml: string }> {
  const extra = {
    options,
    pageContext,
    i18n: ctx.i18n,
    resolvedLocale: ctx.resolvedLocale,
    capabilityRuntime: ctx.capabilityRuntime,
  };
  let headHtml = await applyFilterSafely(ctx, 'frontend:head', '', extra);
  let bodyHtml = await applyFilterSafely(ctx, 'frontend:footer', '', extra);
  return { headHtml, bodyHtml };
}

// ==================== Plugin Configuration ====================

/**
 * Check if a plugin has configuration fields defined in its manifest.
 */
export function pluginHasConfig(pluginId: string): boolean {
  const info = pluginRegistry.get(pluginId);
  if (!info) return false;
  return !!info.manifest.config && Object.keys(info.manifest.config).length > 0;
}

/**
 * Get default values from plugin's config definition.
 * Returns a flat object { fieldName: defaultValue }.
 */
export function getPluginConfigDefaults(pluginId: string): Record<string, any> {
  return getConfigDefaults(pluginRegistry.get(pluginId)?.manifest.config);
}

/**
 * Parse a plugin configuration form according to the plugin manifest.
 */
export function parsePluginConfigFormData(
  configDef: Record<string, PluginConfigField>,
  formData: FormData,
): Record<string, any> {
  return parseConfigFormData(configDef, formData);
}

/**
 * Load plugin configuration from the options table.
 * Key format: "plugin:<pluginId>", value is a JSON string.
 * Falls back to defaults from manifest if not yet saved.
 *
 * @param options - Site options object from loadOptions() (contains all option rows)
 * @param pluginId - Plugin identifier
 * @returns Merged config object (saved values + defaults for missing keys)
 */
export function loadPluginConfig(
  options: Record<string, any>,
  pluginId: string,
): Record<string, any> {
  return loadConfig(options, `plugin:${pluginId}`, pluginRegistry.get(pluginId)?.manifest.config);
}

// ==================== Shared Plugin Utilities ====================

/**
 * Parse a plugin config value from the options store.
 * Handles both raw objects and JSON-encoded strings.
 */
export function parsePluginOption(value: unknown, label?: string): Record<string, unknown> {
  if (!value) return {};
  if (typeof value === 'object') return value as Record<string, unknown>;
  if (typeof value !== 'string') return {};
  try {
    const parsed = JSON.parse(value) as unknown;
    return parsed && typeof parsed === 'object' ? parsed as Record<string, unknown> : {};
  } catch {
    if (label) console.error(`[${label}] Failed to parse plugin config`);
    return {};
  }
}

/**
 * Escape a string for use in HTML attribute values.
 */
export { escapeAttr } from '@/lib/escape';

export { getClientIp } from '@/lib/client-ip';
