import { defineConfig } from 'vitest/config';
import path from 'node:path';
import { sharedAliases } from './vite.shared.mjs';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    setupFiles: ['./tests/setup.ts'],
    include: ['src/**/*.test.ts', 'tests/**/*.test.ts'],
    // Template render tests need the Astro pipeline; they run in the separate
    // project defined by vitest.astro.config.ts (`pnpm run test:astro`).
    exclude: ['**/node_modules/**', '**/dist/**', 'tests/astro/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      include: ['src/lib/**/*.ts', 'src/pages/api/**/*.ts', 'src/plugins/**/*.ts'],
    },
    // Clear cache between tests to avoid cross-test pollution
    env: {
      VITEST: 'true',
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      ...sharedAliases,
      // Stub Cloudflare-specific modules not available in Node.js test env
      'cloudflare:workers': path.resolve(__dirname, './tests/__mocks__/cloudflare-workers.ts'),
      // Stub Astro virtual modules
      'astro:middleware': path.resolve(__dirname, './tests/__mocks__/astro-middleware.ts'),
      // Stub the plugin registry virtual module (real content is generated by the
      // plugin-loader Astro integration at build time)
      'virtual:typecho-plugin-registry': path.resolve(__dirname, './tests/__mocks__/plugin-registry.ts'),
      'virtual:typecho-theme-registry': path.resolve(__dirname, './tests/__mocks__/theme-registry.ts'),
    },
  },
});
