import type { Database } from '@/db';
import type { SiteOptions } from '@/lib/options';

export type TaskKind = 'scheduled' | 'async';
export type TaskSource = 'scheduled' | 'request';

export interface TaskLocalSlot {
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  weekday: number;
  timezone: string;
}

/** Payload generated by the core for every scheduled task invocation. */
export interface ScheduledTaskPayload {
  localSlot: TaskLocalSlot;
  scheduledAt: number;
}

export type TaskResult =
  | { status: 'success'; detail?: string }
  | { status: 'retry'; reason?: string; delaySeconds?: number }
  | { status: 'discard'; reason?: string };

export interface TaskExecutionContext {
  env: Cloudflare.Env;
  db: Database;
  options: SiteOptions;
  pluginId: string;
  taskId: string;
  taskKey: string;
  kind: TaskKind;
  source: TaskSource;
  jobId: string;
  idempotencyKey: string;
  attempt: number;
  scheduledAt: number;
  localSlot: TaskLocalSlot | null;
  signal: AbortSignal;
  log: (message: string, fields?: Record<string, unknown>) => void;
}

export type TaskHandler<TPayload = unknown> = (
  context: TaskExecutionContext,
  payload: TPayload,
) => TaskResult | Promise<TaskResult>;

export interface ScheduledTaskKeyContext {
  scheduledAt: number;
  localSlot: TaskLocalSlot;
}

export interface ScheduledTaskDefinition {
  id: string;
  schedule: string;
  concurrency?: number;
  timeoutSeconds?: number;
  handler: TaskHandler<ScheduledTaskPayload>;
  getTaskKey?: (context: ScheduledTaskKeyContext) => string;
}

export interface AsyncTaskDefinition<TPayload = unknown> {
  id: string;
  concurrency?: number;
  timeoutSeconds?: number;
  handler: TaskHandler<TPayload>;
}

export interface RegisteredScheduledTask
  extends Omit<ScheduledTaskDefinition, 'concurrency' | 'timeoutSeconds'> {
  pluginId: string;
  kind: 'scheduled';
  concurrency: number;
  timeoutSeconds: number;
}

export interface RegisteredAsyncTask<TPayload = unknown>
  extends Omit<AsyncTaskDefinition<TPayload>, 'concurrency' | 'timeoutSeconds'> {
  pluginId: string;
  kind: 'async';
  concurrency: number;
  timeoutSeconds: number;
}

export interface TaskEnvelope {
  schemaVersion: 1;
  jobId: string;
  taskKey: string;
  pluginId: string;
  taskId: string;
  kind: TaskKind;
  source: TaskSource;
  idempotencyKey: string;
  payload: unknown;
  scheduledAt: number;
  enqueuedAt: number;
  localSlot: TaskLocalSlot | null;
}
